language: java

jdk:
#  - oraclejdk8
  - openjdk8

addons:
  sonarcloud:
    organization: "jinahya-github"

script:
  - mvn clean install sonar:sonar

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
                
