language: java
jdk:
  - oraclejdk8

before_install:
install:

before_script:
script:
  - mvn -X clean test
after_success:
after_failure:

before_deploy:
deploy:
after_deploy:

after_script:
                
